### ISSUE TITLE
Error in training opt

### ISSUE THREAD

**Issue by shudong-zhang** [azshue/AutoPoison#1]
`Traceback (most recent call last):
  File "/data/shudong/workspace/shudong/language_models/AutoPoison/main.py", line 332, in <module>
    main()
  File "/data/shudong/workspace/shudong/language_models/AutoPoison/main.py", line 326, in main
    trainer.train()
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/trainer.py", line 1901, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/trainer.py", line 2237, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/trainer.py", line 2294, in _save_checkpoint
    self.save_model(output_dir, _internal_call=True)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/trainer.py", line 2751, in save_model
    save_fsdp_model(self.accelerator.state.fsdp_plugin, self.accelerator, self.model, output_dir)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/accelerate/utils/fsdp_utils.py", line 39, in save_fsdp_model
    state_dict = model.state_dict()
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1815, in state_dict
    self._save_to_state_dict(destination, prefix, keep_vars)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1722, in _save_to_state_dict
    hook(self, prefix, keep_vars)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 669, in _pre_state_dict_hook
    _pre_state_dict_hook_fn[fsdp_state._state_dict_type](
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 271, in _full_pre_state_dict_hook
    _common_unshard_pre_state_dict_hook(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 143, in _common_unshard_pre_state_dict_hook
    _enter_unshard_params_ctx(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 109, in _enter_unshard_params_ctx
    fsdp_state._unshard_params_ctx[module].__enter__()
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/fsdp/_unshard_param_utils.py", line 171, in _unshard_fsdp_state_params
    _validate_unshard_params_args(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/fsdp/_unshard_param_utils.py", line 140, in _validate_unshard_params_args
    raise NotImplementedError(
NotImplementedError: offload_to_cpu=True and NO_SHARD is not supported yet
 16%|██████████████████████████████▏                                                                                                                                                         | 200/1218 [17:47<1:30:32,  5.34s/it]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2118822) of binary: /data/shudong/miniconda3/envs/llm/bin/python
Traceback (most recent call last):
  File "/data/shudong/miniconda3/envs/llm/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-25_01:51:07
  host      : icsl-ai01
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2118822)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
[2023-08-25 01:51:11,435] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/training_args.py:1516: FutureWarning: using `--fsdp_transformer_layer_cls_to_wrap` is deprecated. Use fsdp_config instead
  warnings.warn(
Traceback (most recent call last):
  File "/data/shudong/workspace/shudong/language_models/AutoPoison/main.py", line 332, in <module>
    main()
  File "/data/shudong/workspace/shudong/language_models/AutoPoison/main.py", line 251, in main
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 461, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 983, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/configuration_utils.py", line 617, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/configuration_utils.py", line 672, in _get_config_dict
    resolved_config_file = cached_file(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: ./output/autopoison/opt-1-3b-refusal-output-ns5200-seed0 does not appear to have a file named config.json. Checkout 'https://huggingface.co/./output/autopoison/opt-1-3b-refusal-output-ns5200-seed0/None' for available files.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2123188) of binary: /data/shudong/miniconda3/envs/llm/bin/python
Traceback (most recent call last):
  File "/data/shudong/miniconda3/envs/llm/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-25_01:51:18
  host      : icsl-ai01
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2123188)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
(llm) shudong@icsl-ai01:~/workspace/shudong/language_models/AutoPoison$ bash run.sh
7643
[2023-08-25 17:41:14,603] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/training_args.py:1516: FutureWarning: using `--fsdp_transformer_layer_cls_to_wrap` is deprecated. Use fsdp_config instead
  warnings.warn(
WARNING:root:Loading data...
Reading JSON lines from data/autopoison_gpt-3.5-turbo_refusal_ns5200_from0_seed0.jsonl: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 5200/5200 [00:00<00:00, 149489.58lines/s]
WARNING:root:Formatting inputs...
WARNING:root:Tokenizing inputs... This may take some time...
WARNING:accelerate.accelerator:FSDP Warning: When using FSDP, it is efficient and recommended to call prepare for the model before creating the optimizer
/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/fsdp/_init_utils.py:295: UserWarning: FSDP is switching to use `NO_SHARD` instead of ShardingStrategy.FULL_SHARD since the world size is 1.
  warnings.warn(
WARNING:accelerate.accelerator:FSDP Warning: When using FSDP, several parameter groups will be conflated into a single one due to nested module wrapping and parameter flattening.
{'loss': 1.5242, 'learning_rate': 1.9859901214690094e-05, 'epoch': 0.25}
{'loss': 1.451, 'learning_rate': 1.907459838532215e-05, 'epoch': 0.49}
{'loss': 1.4221, 'learning_rate': 1.7650936695834536e-05, 'epoch': 0.74}
{'loss': 1.4043, 'learning_rate': 1.568906460621502e-05, 'epoch': 0.98}
 33%|█████████████████████████████████████████████████████████████▎                                                                                                                          | 406/1218 [35:55<1:11:29,  5.28s/it]Traceback (most recent call last):
  File "/data/shudong/workspace/shudong/language_models/AutoPoison/main.py", line 332, in <module>
    main()
  File "/data/shudong/workspace/shudong/language_models/AutoPoison/main.py", line 326, in main
    trainer.train()
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/trainer.py", line 1916, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/trainer.py", line 2237, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/trainer.py", line 2294, in _save_checkpoint
    self.save_model(output_dir, _internal_call=True)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/trainer.py", line 2751, in save_model
    save_fsdp_model(self.accelerator.state.fsdp_plugin, self.accelerator, self.model, output_dir)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/accelerate/utils/fsdp_utils.py", line 39, in save_fsdp_model
    state_dict = model.state_dict()
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1815, in state_dict
    self._save_to_state_dict(destination, prefix, keep_vars)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1722, in _save_to_state_dict
    hook(self, prefix, keep_vars)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 669, in _pre_state_dict_hook
    _pre_state_dict_hook_fn[fsdp_state._state_dict_type](
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 271, in _full_pre_state_dict_hook
    _common_unshard_pre_state_dict_hook(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 143, in _common_unshard_pre_state_dict_hook
    _enter_unshard_params_ctx(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 109, in _enter_unshard_params_ctx
    fsdp_state._unshard_params_ctx[module].__enter__()
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/fsdp/_unshard_param_utils.py", line 171, in _unshard_fsdp_state_params
    _validate_unshard_params_args(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/fsdp/_unshard_param_utils.py", line 140, in _validate_unshard_params_args
    raise NotImplementedError(
NotImplementedError: offload_to_cpu=True and NO_SHARD is not supported yet
 33%|█████████████████████████████████████████████████████████████▎                                                                                                                          | 406/1218 [36:03<1:12:07,  5.33s/it]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2208096) of binary: /data/shudong/miniconda3/envs/llm/bin/python
Traceback (most recent call last):
  File "/data/shudong/miniconda3/envs/llm/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-25_18:18:49
  host      : icsl-ai01
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2208096)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
[2023-08-25 18:18:53,675] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/training_args.py:1516: FutureWarning: using `--fsdp_transformer_layer_cls_to_wrap` is deprecated. Use fsdp_config instead
  warnings.warn(
Traceback (most recent call last):
  File "/data/shudong/workspace/shudong/language_models/AutoPoison/main.py", line 332, in <module>
    main()
  File "/data/shudong/workspace/shudong/language_models/AutoPoison/main.py", line 251, in main
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 461, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 983, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/configuration_utils.py", line 617, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/configuration_utils.py", line 672, in _get_config_dict
    resolved_config_file = cached_file(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: ./output/autopoison/opt-1-3b-refusal-output-ns5200-seed0 does not appear to have a file named config.json. Checkout 'https://huggingface.co/./output/autopoison/opt-1-3b-refusal-output-ns5200-seed0/None' for available files.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2214011) of binary: /data/shudong/miniconda3/envs/llm/bin/python
Traceback (most recent call last):
  File "/data/shudong/miniconda3/envs/llm/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/shudong/miniconda3/envs/llm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------

`

**Comment by azshue** [comment]
Hi, 

From the log, the error is caused by the incompatibility between your transformers library and PyTorch. I did a quick search online and found [this same issue](https://github.com/huggingface/transformers/issues/24874) under the transformers repo. I hope this helps. Thanks!

**Comment by shudong-zhang** [comment]
Thank you. I sovled the error by downgrading pytorch->1.13.1.

**Comment by lazyeden** [comment]
Sorry, could you please tell me why I use pytorch 1.13.1, there is a ValueError: FSDP requires PyTorch >= 2.0.1
